services:
  - type: web
    name: cybertorch
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
