services:
  - type: web
    name: telegram-cybernews-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_bot_token_here
      - key: CHAT_ID
        value: your_chat_id_or_channel
