services:
  - type: worker
    name: cybernews-telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    build:
      pythonVersion: 3.10
